/** Snapshot of backend/app/metrics.py LOCKED_LABELS. Order is the product contract. */
export const LOCKED_LABELS = [
  "Owner Earnings / Last Close Price",
  "Cash per Share / Last Close Price",
  "Dividends per Share / Last Close Price",
  "Net Income per Share / Last Close Price",
  "Equity per Share / Last Close Price",
  "Assets per Share / Last Close Price",
  "Revenue per Share / Last Close Price",
  "Net Income / Equity",
  "Net Income / Assets",
  "Net Income / Revenue",
  "Net Income / Total Liabilities",
  "Net Income / Debt",
  "Owner Earnings / Equity",
  "Owner Earnings / Assets",
  "Owner Earnings / Revenue",
  "Owner Earnings / Total Liabilities",
  "Owner Earnings / Debt",
  "Dividends / Equity",
  "Dividends / Owner Earnings",
  "Dividends / Net Income",
  "Owner Earnings per Share",
  "Cash per Share",
  "Dividends per Share",
  "Net Income per Share",
  "Equity per Share",
  "Assets per Share",
  "Revenue per Share",
  "Liabilities per Share",
  "Debt per Share",
  "Shares Outstanding",
  "30 Year Treasury (DGS30)",
  "Owner Earnings / 30 Year Treasury per Share",
] as const;

export type LockedLabel = (typeof LOCKED_LABELS)[number];
